### ISSUE TITLE
Error onepub login command

### ISSUE THREAD

**Issue by PKeviin** [onepub-dev/onepub#122]
Hello, I have an error when I try to connect with the command "onepub login".
I'm trying to sign in with google chrome and a google account.

It might be cache related.
I added ```export PATH="$PATH":"$HOME/.pub-cache/bin"``` to my .zshrc file.

```
kevin@macbook template % onepub login      
OnePub version: 1.4.5 

To login to OnePub...

From a web browser, go to: 
https://onepub.dev/clilogin

Waiting for your authorisation...
Authorisation received, processing...
ERROR - 2022-09-15 01:10:07.667865
Asynchronous error
FormatException: Missing extension byte (at offset 259)
dart:convert                                                                       Utf8Codec.decode
package:onepub/src/util/send_command.dart 122:23                                   _processData.<fn>
dart:cli                                                                           waitFor
package:dcli/src/util/wait_for_ex.dart 26:17                                       waitForEx
package:onepub/src/entry_point.dart 37:9                                           entrypoint.<fn>
package:onepub/src/onepub_settings.dart 158:13                                     withSettings.<fn>
dart:async                                                                         runZoned
package:scope/src/scope.dart 109:12                                                Scope.run
package:onepub/src/onepub_settings.dart 157:7                                      withSettings
package:onepub/src/entry_point.dart 33:5                                           entrypoint
/Users/kevin/.pub-cache/hosted/pub.dartlang.org/onepub-1.4.5/bin/onepub.dart 17:9  main
```

Onepub doctor 

```
kevin@macbook template % onepub doctor
OnePub version: 1.4.5 

Platform
OS              macos                              
OS version        Version 12.5.1 (Build 21G83)
Path separator  /                                  

Dart version: 2.18.0
Dart path: /opt/homebrew/bin/dart


URLs
Web site: https://onepub.dev/
API endpoint: https://onepub.dev/api

Environment
PUB_CACHE: not set and not used.
PATH
                /<HOME>/dev/google-cloud-sdk/bin    
                /<HOME>/.nvm/versions/node/v16.14.2 
                /opt/homebrew/bin                   
                /usr/local/bin                      
                /usr/bin                            
                /bin                                
                /usr/sbin                           
                /sbin                               
                /<HOME>/dev/flutter/bin             
                /Library/Apple/usr/bin              
                /<HOME>/.pub-cache/bin              
                /dev/flutter/bin                     ERROR: path does not exist.

Shell Settings
$SHELL          /bin/zsh                           
detected        zsh                                
Start script    /<HOME>/.zshrc                     

Repository tokens
No tokens found.

Status
You are not logged into OnePub.
run: onepub login
checking status...  
OnePub: status healthy.
```

**Comment by bsutton** [comment]
@PKeviin we have just released onepub 2.0.

Can you please upgrade your onepub cli tools:

```bash
dart pub global activate onepub
```
The run login:
```
onepub login
```

Please let me know how it goes.

If you are interested we have released an 'experimental' package discussion thread.

If you search for a public or private package in onepub and open the package details view there is a new tab 'discussions' just after the readme.

**Comment by bsutton** [comment]
So a couple of minor items:

PUB_CACHE:      not set and not used.

This is expected. It just means that you have overridden the location of PUB_CACHE.
I will try to revise the wording in away that this won't raise a flag.

The PATH error will be correct:
/dev/flutter/bin                     ERROR: path does not exist

Check your PATH and you will find /dev/flutter/bin on your path but that directory doesn't exist.

However, this won't be causing any problems.

Can I get you to run:

```bash
onepub -d login
```
This will output debug traces which help us see which command caused the error.

The error seems to suggest that the returning stream has become altered in some way or isn't json.
Are you running a proxy or have any other 'oddities' in how you connect to the internet?

**Comment by bsutton** [comment]
I just boot up my old mac (10.15.7) running dart 2.17 and the login works.

So its not a simple as 'its a mac thing'.

I will try again after upgrading my mac to dart 2.18.0.

**Comment by bsutton** [comment]
So I've tested with 2.18.1 and 2.18.0 on my mac and everything works fine.

It's interesting to see that onepub doctor is working as it uses sendcommand to get the server status/version.

**Comment by bsutton** [comment]
Just a thought - I assume your mac is running english?

**Comment by bsutton** [comment]
So I'm pretty certain it's not a browser issue as the problem is with the onepub command sending requests to our server (browser has no interaction with this path).

I can't reproduce this locally so I've just pushed a new version of the onepub command.

If you run:

```bash
dart pub global activate onepub
onepub -d login
```
the reported version should be 2.0.1

We should now see exactly what data is being sent/returned.

**Comment by bsutton** [comment]
> No in french, It is a problem?

It shouldn't, but you do have that little glyph(?) above the e in your name.
I'm wondering if the utf8 decoder can't handle it.

**Comment by bsutton** [comment]
So your organisation name is Pastor Kévin.
We return this post login.

I've done some tests and it's the accent causing the issue.

For some reason, the server is setting the incorrect charset (latin vs utf-8) despite our code setting it explicitly.

If all goes well I should have a solution tomorrow.

**Comment by bsutton** [comment]
We have a fix.
Turns out we were setting the UTF-8 charset after we obtained the response writer.
Once the response write is obtained its too late to set the character encoder.

This is a server-side fix so I'm pushing out a fix.

It should be deployed within the next hour or so.

Just try the login again and let me know how you go.

Greatly appreciate your help in getting this one fixed!

Now if you can just get the french government to get rid of those silly accents :D

**Comment by bsutton** [comment]
Kevin,
the production server has been updated.

If you can try logging  in and let me know how it goes.
