### ISSUE TITLE
Example tab isn't formatted with markdown

### ISSUE THREAD

**Issue by ahmednfwela** [onepub-dev/onepub#194]
Current example tab doesn't wrap the code with 
\```dart 
\```
so it appears as unformatted.
current UI:
![image](https://user-images.githubusercontent.com/63286031/203293562-062ba6b9-c74c-4aa3-84b1-b9c94f380a46.png)

**Comment by bsutton** [comment]
Thanks for the feedback.

We have a fix for this which will be pushed to production early next week.
