### ISSUE TITLE
Cannot create new team; Nowhere to add member

### ISSUE THREAD

**Issue by isaac-gofa** [onepub-dev/onepub#301]
![image](https://user-images.githubusercontent.com/126567837/225811297-9a720947-25cd-451f-9075-b3492f305b2f.png)
![image](https://user-images.githubusercontent.com/126567837/225811435-438e8090-dc74-4778-b243-65004279e187.png)

**Comment by bsutton** [comment]
Isaac,
just trying to understand the problem, so hope you can give me some more detail.

The first error 'There must be a Team Leader' requires that you click on the 'Leaders' tab and select a user
to be the Team leader.

I'm trying to understand if:
1) you were unable to assign a leader
2) the instructions were not clear and you didn't realize you needed to assign a leader

As to 'Adding a Member'.

You add members by using the 'Invite' button on the home page.
![image](https://user-images.githubusercontent.com/900408/225815141-e53245c9-b504-4d12-bd13-4acba09d45b7.png)

I can see we need to make this clearer.
Did you discover the '...' menu on the Members view?
I'm thinking we could add an 'Invite Member' option under that menu that triggered the Invite Wizard (as the home page does).
Would that make sense to you?

**Comment by bsutton** [comment]
Add Invite Member to the Member page.
