### ISSUE TITLE
Gitignore filter to pub.dev ?

### ISSUE THREAD

**Issue by redDwarf03** [onepub-dev/onepub#311]
Hello

Are you agree to externalize the Ignore class to a lib on pub.dev ?
https://github.com/onepub-dev/onepub/blob/1ff7e81d450ebcab984bc9a3f69b224941e20f6d/lib/src/pub/ignore.dart

It could be useful to have a lib to manage filter from a gitignore file like js lib https://www.npmjs.com/package/parse-gitignore?activeTab=code

Thank you

**Comment by bsutton** [comment]
Sorry, but I don't understand what you are asking.

Have you come to the right place?

OnePub is a private dart package repository.  If you want changes to pub.dev
you need to go to https://github.com/dart-lang/pub.

**Comment by redDwarf03** [comment]
hello. ok i will go to pub repo.
Sorry
