### ISSUE TITLE
Can't login to onepub CLI due to billing problems

### ISSUE THREAD

**Issue by ahmednfwela** [onepub-dev/onepub#348]
**Describe the bug**
I had an account during the beta, and uploaded more than 1 package, so I received the lifetime Pro plan.
However I am facing the following problems:

1. When I login to the website, I am getting a warning "Your plan has expired"
2. in the [Account](https://onepub.dev/Account) page, it shows under the price calculator that my plan has expired 
  ![image](https://user-images.githubusercontent.com/63286031/230981648-2e61f4e4-c8c1-4e27-b5d2-fd006317d6fa.png)
  as you can see here, I have `Next Renewal: Past Due`
3. When I try logging in via OnePub CLI, I get :
```
Login failed: Your OnePub subscription has not been paid.       
To manage your subscription goto https://onepub.dev/Account/Plan
```
and sometimes I get this:

![image](https://user-images.githubusercontent.com/63286031/230981082-ab9a8227-b839-431c-ac11-fabc58cfb2b7.png)

This is preventing me from doing `onepub get` and I can't run any project

**Comment by ahmednfwela** [comment]
cc @bsutton

**Comment by bsutton** [comment]
So your problem with the expired subscription is that you have 1 free pro license but 2 registered members.

The free 'pro' subscription is only available to each person that uploads.

So you have two choices.
1) purchase 1 pro license.
2) downgrade to the free tier.

As to the bug, I've asked the dev team to investigate it and will report back.
Apologies for the inconvenience.

Brett

**Comment by ahmednfwela** [comment]
oh I thought it applied to the entire organization, that's why I didn't bother asking my teammates to upload packages themselves

**Comment by bsutton** [comment]
Just an update on the error message.

The team believes they have found the error and we expect to push an update by the end of the week all going well.

If you have any other issues please let us know.
