### ISSUE TITLE
Contact OnePub button opens a read-only dialog

### ISSUE THREAD

**Issue by ahmednfwela** [onepub-dev/onepub#349]
Clicking on Contact OnePub on the website opens this dialog 
![image](https://user-images.githubusercontent.com/63286031/230985113-19a1fb92-d161-4753-884d-81990471011e.png)

It's readonly, and can't be edited

**Comment by bsutton** [comment]
Thanks for the feedback.
I've got the devs looking into it.
We should have a fix applied later this week.

**Comment by bsutton** [comment]
Just confirming that we have found and fixed the bug.
Should be deployed by friday.
