### ISSUE TITLE
UUID: 2797787047 1.39.1 Cannot invoke "com.vaadin.flow.component.textfield.TextField.setReadOnly(boolean)" because "this.name" is null

### ISSUE THREAD

**Issue by bsutton** [onepub-dev/onepub#38]
Automated Issue Generator

An error occurred with a stack hash of 2797787047.

The hash has been reported to the user who is encourage to add notes to this issue
regarding the circumstances that it occurred under.

Additional details are stored in a mirror image within OnePub's private repository to avoid
disclosing details that may expose sensitive information.

The internal issue is: https://github.com/onepub-dev/onepub-vaadin/issues/298

**Comment by rlsutton1** [comment]
fixed
