### ISSUE TITLE
failed to onepub login

### ISSUE THREAD

**Issue by isaac-gofa** [onepub-dev/onepub#441]
**Describe the bug**
Forever waiting for your authorizing...
even after I logged in successfully in Chrome and close the browser. 
Tried in Edge, same.

**To Reproduce**
1. onepub logout
2. onepub login

**Expected behavior**
Should log in successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/126567837/236392386-75a1f827-931a-4031-ae04-7620eb8827fa.png)

** Problems with CLI tooling **
If your issue is with the OnePub CLI tooling then:

Run onepub doctor and post the output here:

```
onepub doctor
PS C:\Users\isaac\source\repos\gofa_sdk\packages\gofa_pose> onepub doctor
OnePub version: 3.1.0 

Platform
Dart version:   2.19.6
Dart path:      /usr/bin/dart

OS:             windows
OS version:     "Windows 10 Pro" 10.0 (Build 22621)

Locale:         en-US
Path separator: \


URLs
Web site:       https://onepub.dev/
API endpoint:   https://onepub.dev/api/fvnuhnofly/ 

Environment
Pub Cache:      C:\Users\isaac\AppData\Local\Pub\Ca
PUB_CACHE:      not set and not used.
PATH:
                C:\src\flutter\bin
                C:\Program Files\Common Files\Oracl
                C:\<HOME>\npm
                C:\Program Files (x86)\Intel\Intel(
                C:\Program Files\Intel\Intel(R) Man
                C:\WINDOWS\system32
                C:\WINDOWS
                C:\WINDOWS\System32\Wbem
                C:\WINDOWS\System32\WindowsPowerShe
                C:\Program Files\dotnet
                C:\Program Files\Git\cmd
                C:\Users\isaac\AppData\Local\Androi
                C:\Users\isaac\.windows-build-tools
                C:\Users\isaac\AppData\Local\Micros
                C:\Users\isaac\source\repos\gofa_sd  ERROR: path is blank.
                C:\Users\isaac\AppData\Local\Progra
                C:\Users\isaac\AppData\Local\Micros
                C:\<HOME>\Composer\vendor\bin        ERROR: path does not exist.
                C:\Program Files (x86)\Sophos\Sopho
                C:\Program Files\Azure Data Studio\
                C:\Users\isaac\.dotnet\tools         ERROR: path does not exist.
                C:\<HOME>\npm

Shell Settings
$SHELL:
Detected:       cmd.exe
Start script:   not supported by shell

Repository tokens
Not logged into OnePub.

Status
You are not logged into OnePub.
run: onepub login
checking status...
OnePub: status healthy.

Server Version: 3.95.1
```

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: chrome, edge
 - chrome version: Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by bsutton** [comment]
When you go to login to the web ui does it ask you to choose what
organisation you are logging into?

**Comment by bsutton** [comment]
just letting you know that we have managed to reproduce the problem.

Team is working on a fix.
Hope to have a fix within the next hour.
Will update you when resolved.

**Comment by isaac-gofa** [comment]
I dont need to select organization, and at the top right side, there's a
prompt to let me select google login or whatever. And i chose google login.

Isaac Chan
Project Manager/ Software Engineer
T: 93443553

GF Lab International Limited
Room B11, 5/F, Block B, Hong Kong Industrial Centre,

No. 489-491 Castle Peak Road, Kowloon, Hong Kong

香港九龍青山道489-491 號香港工業中心B座5樓11室

**Comment by bsutton** [comment]
Isaac, 
we have a fix.
the team are in the process of deploy it.
It will be deployed within the next 15 minutes.
apologies for the inconvenience.

**Comment by isaac-gofa** [comment]
Thanks for quick reply. Appreciate it.

Isaac Chan
Project Manager/ Software Engineer
T: 93443553

GF Lab International Limited
Room B11, 5/F, Block B, Hong Kong Industrial Centre,

No. 489-491 Castle Peak Road, Kowloon, Hong Kong

香港九龍青山道489-491 號香港工業中心B座5樓11室

**Comment by bsutton** [comment]
the fix is deployed.

Once again, apologies for the pain.

I will close this ticket, but open a new one if you have any issues.
