### ISSUE TITLE
I cannot reassign a member to a different team.

### ISSUE THREAD

**Issue by isaac-gofa** [onepub-dev/onepub#459]
**Describe the bug**
I cannot create a new team. 
the new team requires me to select at least one member.
but when I select isaacchan@zaccdev.com.hk,
the error message appears saying isaacchan@zacdev.com.hk cannot be a member of EVERYONE. 

I want to create a team called "ZACDEV" and move this isaacchan@zacdev.com.hk to it. 

**To Reproduce**
1. create a new team. 
2. input ZACDEV as team name
3. select isaac.c@gofa.co as leader
4. select isaacchan@zaccdev.com.hk as member
5. save
6. See error

**Expected behavior**
A new team should be created called "ZACDEV", with isaacchan@zacdev.com.hk as a member.

**Screenshots**
![image](https://github.com/onepub-dev/onepub/assets/126567837/c5ca232f-1349-41f9-89ab-7d904c2a85d3)

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by bsutton** [comment]
Thanks for the bug report.

The team will be looking at this problem this morning.

Will update you in a few hours.

**Comment by bsutton** [comment]
Isaac,

I'm trying to work out how you got in this state.

The account issacchan@zacdev.com.hk has the 'Customer' role and I can see the associated invite.

The invite adds him to the 'GOFA Team' team but not the EveryOne team (because we don't allow this).

What I don't understand is how issacchan@zacdev.com.hk became a member of the Everyone team.

Can you provide an additional information on the actions you took between inviting issacchan@zacdev.com.hk and trying to add him to the ZACDEV team?

**Comment by bsutton** [comment]
Isaac,
just a follow up. We do need to get to the bottom of this as we view it as a failure of the security system.
Customers having access to the Everyone team is a breach of the security model and can lead to packages being leaked (to that member).

So any info you can provide on actions take is greatly appreciated.

Brett

**Comment by bsutton** [comment]
Isaac,
we found the problem.
At some point you had renamed the Everyone team to GOFA Team.
You then recreated a new Everyone team.
The problem with this is we actually use an 'everyone' flag to determine the Everyone team, so GOFA Team was being treated as the Everyone team.

Some time ago we had removed the ability to rename the Everyone team.

So in sort the problem wasn't a security breach and there was no leakage.

We have reset your Everyone team so it is once again the actual Everyone team.
It looks to me like you have already resolved the issue of adding the new team member so I think everything is now resolved.

So the sort story is, no security breach, the problem can't happen again and you are up and running.

I will close this issue out, but if you have any further issues or questions please feel free to re-open the issue.

**Comment by isaac-gofa** [comment]
Thanks for the help. Yes, I have found a workaround to create the ZACDEV
team. Good to know it's fixed.

Isaac Chan
Project Manager/ Software Engineer
T: 93443553

GF Lab International Limited
Room B11, 5/F, Block B, Hong Kong Industrial Centre,

No. 489-491 Castle Peak Road, Kowloon, Hong Kong

香港九龍青山道489-491 號香港工業中心B座5樓11室
