### ISSUE TITLE
Cannot install OnePub CLI by "onepub pub global activate onepub"

### ISSUE THREAD

**Issue by isaac-gofa** [onepub-dev/onepub#475]
**Describe the bug**
Cannot install OnePub CLI by "onepub pub global activate onepub"

**To Reproduce**
1. run "onepub pub global activate onepub" in CLI

**Expected behavior**
should install OnePub CLI successfully.

** Problems with CLI tooling **
If your issue is with the OnePub CLI tooling then:

PS C:\Users\isaac\source\repos\gofa_test_depend_gofa_pose> flutter doctor -v
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\isaac\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33530.505
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\isaac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (5 available)
    • V2046 (mobile)             • 3061250798005QE • android-arm64  • Android 13 (API 33)
    • sdk gphone x86 64 (mobile) • emulator-5554   • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows         • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)               • chrome          • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)                 • edge            • web-javascript • Microsoft Edge 112.0.1722.68

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\Users\isaac\source\repos\gofa_test_depend_gofa_pose> 

**Additional context**

PS C:\Users\isaac\source\repos\gofa_test_depend_gofa_pose> dart pub global activate onepub    
+ _fe_analyzer_shared 26.0.0 (60.0.0 available)
+ analyzer 2.3.0 (5.12.0 available)
+ archive 3.3.0 (3.3.7 available)
+ args 2.3.1 (2.4.1 available)
+ async 2.8.2 (2.11.0 available)
+ basic_utils 3.8.0 (5.5.4 available)
+ boolean_selector 2.1.0 (2.1.1 available)
+ charcode 1.3.1
+ chunked_stream 1.4.1 (1.4.2 available)
+ circular_buffer 0.9.1 (0.11.0 available)
+ cli_util 0.3.5 (0.4.0 available)
+ collection 1.15.0 (1.17.2 available)
+ convert 3.1.0 (3.1.1 available)
+ coverage 1.0.3 (1.6.3 available)
+ crypto 3.0.1 (3.0.3 available)
+ csv 5.0.1 (5.0.2 available)
+ dart_console 1.0.0 (1.2.0 available)
+ dcli 1.22.1 (2.2.1 available)
+ dcli_core 1.22.1 (2.2.1 available)
+ equatable 2.0.3 (2.0.5 available)
+ ffi 1.2.1 (2.0.2 available)
+ file 6.1.4
+ file_utils 1.0.1
+ frontend_server_client 2.1.2 (3.2.0 available)
+ glob 2.0.1 (2.1.1 available)
+ globbing 1.0.0
+ http 0.13.3 (0.13.6 available)
+ http_multi_server 3.0.1 (3.2.1 available)
+ http_parser 4.0.0 (4.0.2 available)
+ ini 2.1.0
+ io 1.0.3 (1.0.4 available)
+ js 0.6.3 (0.6.7 available)
+ json_annotation 4.1.0 (4.8.1 available)
+ logging 1.0.2 (1.1.1 available)
+ meta 1.8.0 (1.9.1 available)
+ mime 1.0.2 (1.0.4 available)
+ node_preamble 2.0.1 (2.0.2 available)
+ oauth2 2.0.0 (2.0.1 available)
+ onepub 3.1.0
+ package_config 2.1.0
+ path 1.8.1 (1.8.3 available)
+ pedantic 1.11.1
+ pointycastle 3.6.0 (3.7.3 available)
+ pool 1.5.0 (1.5.1 available)
+ posix 2.2.3 (5.0.0 available)
+ pub_semver 2.1.2 (2.1.4 available)
+ pubspec2 2.4.2
+ random_string 2.3.1
+ scope 3.0.0 (4.0.0 available)
+ settings_yaml 3.5.1 (6.0.0 available)
+ shelf 1.2.0 (1.4.1 available)
+ source_map_stack_trace 2.1.0 (2.1.1 available)
+ source_maps 0.10.10 (0.10.12 available)
+ source_span 1.8.1 (1.10.0 available)
+ stack_trace 1.10.0 (1.11.0 available)
+ stacktrace_impl 2.3.0
+ stream_channel 2.1.0 (2.1.1 available)
+ string_scanner 1.1.1 (1.2.0 available)
+ strings_xxx 1.0.0
+ system_info2 2.0.4 (4.0.0 available)
+ term_glyph 1.2.1
+ typed_data 1.3.0 (1.3.2 available)
+ url_builder 1.0.0 (2.0.0 available)
+ usage 4.0.2 (4.1.1 available)
+ uuid 3.0.6 (3.0.7 available)
+ validators2 3.0.0 (5.0.0 available)
+ vin_decoder 0.2.1-nullsafety
+ vm_service 7.5.0 (11.6.0 available)
+ watcher 1.0.0 (1.1.0 available)
+ web_socket_channel 2.2.0 (2.4.0 available)
+ webkit_inspection_protocol 1.1.0 (1.2.0 available)
+ win32 2.0.5 (5.0.0 available)
+ yaml 3.1.0 (3.1.2 available)
+ yaml_edit 2.0.2 (2.1.1 available)
Building package executables... (15.5s)
Failed to build onepub:opub:
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:723:40: Error: Field '_unique___locales_item_0' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_0;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:724:40: Error: Field '_unique___locales_item_1' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_1;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:725:40: Error: Field '_unique___locales_item_2' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_2;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:726:40: Error: Field '_unique___locales_item_3' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_3;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:727:40: Error: Field '_unique___locales_item_4' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_4;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:728:40: Error: Field '_unique___locales_item_5' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_5;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:729:40: Error: Field '_unique___locales_item_6' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_6;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:730:40: Error: Field '_unique___locales_item_7' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_7;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:731:40: Error: Field '_unique___locales_item_8' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_8;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:732:40: Error: Field '_unique___locales_item_9' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_9;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:733:40: Error: Field '_unique___locales_item_10' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_10;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:734:40: Error: Field '_unique___locales_item_11' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_11;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:735:40: Error: Field '_unique___locales_item_12' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_12;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:741:35: Error: Field '_unique___names_item_0' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_0;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:742:35: Error: Field '_unique___names_item_1' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_1;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:743:35: Error: Field '_unique___names_item_2' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_2;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:744:35: Error: Field '_unique___names_item_3' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_3;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:745:35: Error: Field '_unique___names_item_4' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_4;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:746:35: Error: Field '_unique___names_item_5' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_5;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:747:35: Error: Field '_unique___names_item_6' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_6;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:748:35: Error: Field '_unique___names_item_7' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_7;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:749:35: Error: Field '_unique___names_item_8' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_8;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:750:35: Error: Field '_unique___names_item_9' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_9;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:751:35: Error: Field '_unique___names_item_10' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_10;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:752:35: Error: Field '_unique___names_item_11' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_11;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:753:35: Error: Field '_unique___names_item_12' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_12;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:296:35: Error: Field 'gr_name' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? gr_name;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:299:35: Error: Field 'gr_passwd' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? gr_passwd;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:303:17: Error: Field 'gr_gid' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? gr_gid;
                ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:306:48: Error: Field 'gr_mem' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Pointer<ffi.Int8>>? gr_mem;
                                               ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:291:35: Error: Field 'pw_name' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_name;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:295:35: Error: Field 'pw_passwd' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_passwd;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:299:17: Error: Field 'pw_uid' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? pw_uid;
                ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:303:17: Error: Field 'pw_gid' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? pw_gid;
                ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:306:35: Error: Field 'pw_gecos' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_gecos;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:309:35: Error: Field 'pw_dir' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_dir;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:312:35: Error: Field 'pw_shell' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_shell;
                                  ^
Failed to build onepub:onepub:
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:723:40: Error: Field '_unique___locales_item_0' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_0;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:724:40: Error: Field '_unique___locales_item_1' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_1;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:725:40: Error: Field '_unique___locales_item_2' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_2;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:726:40: Error: Field '_unique___locales_item_3' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_3;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:727:40: Error: Field '_unique___locales_item_4' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_4;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:728:40: Error: Field '_unique___locales_item_5' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_5;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:729:40: Error: Field '_unique___locales_item_6' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_6;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:730:40: Error: Field '_unique___locales_item_7' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_7;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:731:40: Error: Field '_unique___locales_item_8' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_8;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:732:40: Error: Field '_unique___locales_item_9' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_9;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:733:40: Error: Field '_unique___locales_item_10' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_10;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:734:40: Error: Field '_unique___locales_item_11' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_11;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:735:40: Error: Field '_unique___locales_item_12' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<__locale_data>? _unique___locales_item_12;
                                       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:741:35: Error: Field '_unique___names_item_0' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_0;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:742:35: Error: Field '_unique___names_item_1' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_1;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:743:35: Error: Field '_unique___names_item_2' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_2;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:744:35: Error: Field '_unique___names_item_3' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_3;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:745:35: Error: Field '_unique___names_item_4' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_4;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:746:35: Error: Field '_unique___names_item_5' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_5;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:747:35: Error: Field '_unique___names_item_6' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_6;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:748:35: Error: Field '_unique___names_item_7' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_7;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:749:35: Error: Field '_unique___names_item_8' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_8;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:750:35: Error: Field '_unique___names_item_9' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_9;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:751:35: Error: Field '_unique___names_item_10' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_10;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:752:35: Error: Field '_unique___names_item_11' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_11;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/string/string.dart:753:35: Error: Field '_unique___names_item_12' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? _unique___names_item_12;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:296:35: Error: Field 'gr_name' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? gr_name;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:299:35: Error: Field 'gr_passwd' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? gr_passwd;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:303:17: Error: Field 'gr_gid' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? gr_gid;
                ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/grp.dart:306:48: Error: Field 'gr_mem' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Pointer<ffi.Int8>>? gr_mem;
                                               ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:291:35: Error: Field 'pw_name' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_name;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:295:35: Error: Field 'pw_passwd' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_passwd;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:299:17: Error: Field 'pw_uid' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? pw_uid;
                ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:303:17: Error: Field 'pw_gid' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? pw_gid;
                ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:306:35: Error: Field 'pw_gecos' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_gecos;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:309:35: Error: Field 'pw_dir' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_dir;
                                  ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/posix-2.2.3/lib/src/pwd.dart:312:35: Error: Field 'pw_shell' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external ffi.Pointer<ffi.Int8>? pw_shell;
                                  ^
PS C:\Users\isaac\source\repos\gofa_test_depend_gofa_pose>

**Comment by bsutton** [comment]
Isaac,
we are aware of the problem and in the process of getting an update released.

just have a few complications with dependencies that are not yet 3.x aware.

expecting to have something out in the next two days.

Will keep you updated.

**Comment by bsutton** [comment]
Isacc,
so some good news.

The team have pushed a beta out.
We know there is still a problem with the `onepub pub add` command but the login/export/import process should now be working as expected.
Can you give the beta a run and let us know how it goes.
We continue to work through the remaining issues.

You can install the beta by running:

```
dart pub global activate onepub 4.0.0-beta.2
```

**Comment by bsutton** [comment]
Isaac,
we have released onepub 4.0 which resolves all of the dart 3.x issues.

Can you please upgrade to the latest version and let us know if you have any problems.

I will close this issue but feel free to reopen it if you have any problems.
