### ISSUE TITLE
Azure devops to onepub authentication getting failed.

### ISSUE THREAD

**Issue by pas1405** [onepub-dev/onepub#535]
**Describe the bug**
Hi,
we have onepub package available in onepub repo, we trying to deploy that using on azure pipeline. 
Check the Below link, I followed to export the Auth token Yaml.
URL : https://docs.onepub.dev/guides/cli-integration/export
CLI tool: I try to login with one pub login (CMD)) screen, but its getting disappears.
 **What we are trying to do:**
 Azure Pipeline (CI CD). By doing so in the classic editor and running the pipeline, we are unable to reach the one pub package, we have created one CICD user in onepubdev
Email : parasu@cicd.kijxxpsdav.onepub.dev
Auth token : ( last 4 digit ) yYTY

check the attached screen shots for failed build.

![onepub 2](https://github.com/onepub-dev/onepub/assets/149512287/9436abff-8861-406d-b9c9-ccbb20394ae6)
![onepub1](https://github.com/onepub-dev/onepub/assets/149512287/1b90892a-0361-4ddb-866c-cf689c390957)

**Expected behavior**

**Screenshots**

** Problems with CLI tooling **
If your issue is with the OnePub CLI tooling then:

Run onepub doctor and post the output here:

```
onepub doctor - cmd not get executed
```

If you are having path problems then run:
```
<path to dart>/dart pub global run  onepub:onepub doctor - Cmd not getting executed.

**Comment by bsutton** [comment]
Completed
