### ISSUE TITLE
TeamLeader members visibility 

### ISSUE THREAD

**Issue by tudordanbalas** [onepub-dev/onepub#538]
**Describe the bug**
As a team leader inside a team, you can't see team members, or manage/see CI/CD that is part of the team.

**To Reproduce**
1. Create a new user
2. Give it TeamLeader role
3. Assign it to the team
4. Check members tab

**Expected behavior**
I expect to see other team members, also the CI/CD account under that specific team and be able to manage it.

**Comment by bsutton** [comment]
Thanks for the bug report. Will get the team to investigate.
Probably take a week to turn around a fix.

**Comment by bsutton** [comment]
We are wondering if you missed a step.

You need to mark the member as a 'Leader' on the Teams screen.

Giving the Member the role of team leader isn't sufficient. You actually need to mark them as a 'Team Leader' on the Teams 'Leaders' tab.

It also looks like we were missing any doco on this subject (apologies):

This should help:
https://docs.onepub.dev/workflows/creating-a-team-leader

Let me know if this doesn't resolve your issue.

**Comment by tudordanbalas** [comment]
And what role does a Member need to Export the token for the CICD in the team?

**Comment by bsutton** [comment]
Tudor,
sorry about the delay.

To export a token (other than your own) you need to be an administrator or
a Team leader (of the team that the ci/cd member is associated with).

Brett

**Comment by bsutton** [comment]
https://docs.onepub.dev/guides/ci-cd

**Comment by tudordanbalas** [comment]
Just tested and as a TeamLeader you don't have the option to export the token on your own team; only to invalidate it

**Comment by bsutton** [comment]
So sounds like a bug.

Have you tried it via the cli?

**Comment by bsutton** [comment]
Which user did you use?

**Comment by tudordanbalas** [comment]
Check out for user marius[dot]gutoi[at]swiftmedical[dot]com

**Comment by bsutton** [comment]
tudor,
this is should now be resolved.
Any issues please feel free to re-open this issue.

**Comment by bsutton** [comment]
Tudor,
just follow up to confirm that we solved your problem?
Brett

**Comment by tudordanbalas** [comment]
Yes, all good. Thanks!
