### ISSUE TITLE
OnePub does not accept requests from third party pub clients

### ISSUE THREAD

**Issue by JonathanKohlhas** [onepub-dev/onepub#539]
**Describe the bug**
When trying to access OnePubs pub server using a third party pub client, OnePub will reject connections when checking the user agent and send out an email about using an old dart version. The pub specification does not include a restriction on the content of the useragent header. 

**To Reproduce**
1. Install Melos monorepo tool 
2. Set up a package in the monorepo
3. Publish package to onepub using normal "dart pub"
4. Use "melos version" (should update version numbers based on last published version) fails because the version of the package cannot be checked

**Expected behavior**
Third party clients should not be rejected by the useragent header check. I would expect the check to only happen if the user agent is a dart pub one and not for third party clients

**Comment by bsutton** [comment]
So we weren't aware that melos had a pub client built into it.

The reason for the agent check was to ensure that the user was using a compatible version of pub publish (there was a spec change around 2.15).

The team are going to relax the rules a little so we can support third party agents.
Probably take a week to get into release (unless we get lucky and it gets drop into the current release train).



I

**Comment by bsutton** [comment]
Jonathan,
this issue should now be resolved.

Feel free to re-open this issue if you find any problems.

**Comment by bsutton** [comment]
Jonathan,
just following up to check that we have solved the issue for you?

Brett
