### ISSUE TITLE
Onepub is down?

### ISSUE THREAD

**Issue by tudordanbalas** [onepub-dev/onepub#541]
Onepub is down?

**Comment by schnaser-pcc** [comment]
Same here: https://downforeveryoneorjustme.com/onepub.dev

**Comment by bsutton** [comment]
Tudor,
apologies we have had an outage.

All services are now restored.

We are investigating the cause.

Brett.

**Comment by bsutton** [comment]
and backup up.

sorry we are still investigating the cause.
