### ISSUE TITLE
Can't invite new members

### ISSUE THREAD

**Issue by tudordanbalas** [onepub-dev/onepub#543]
When trying to invite a new collaborator to our team, this is the message I get:
dev.onepub.util.internet.email.EmailException: 550-5.4.5 Daily user sending limit exceeded. For more information on Gmail 550-5.4.5 sending limits go to 550 5.4.5 https://support.google.com/a/answer/166852 d75a77b69052e-4535f85b3d9sm7257481cf.29 - gsmtp

**Comment by bsutton** [comment]
Tudor,

Let me investigate and get back to you.

**Comment by bsutton** [comment]
you should be able to do it now.

Part of sunday's upgrade is changing our email path to avoid the limit you
hit.

Brett

**Comment by tudordanbalas** [comment]
All good now. Thanks!
